version: '3.7'

services:
  walaboratorio_web:
    image: node:16.14
    container_name: walaboratorio_api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - walaboratorio-network
    links:
      - db
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: 'yarn dev:server'
  db:
    image: postgres:13.4
    container_name: walaboratorio_db
    environment:
      POSTGRES_PASSWORD: dev123
      POSTGRES_USER: postgres
      PGDATA: /tmp
    ports:
      - "54320:5432"
    volumes:
      - $HOME/Data/postgres:/var/lib/postgresql/data
      - ./Docker/SQL/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - walaboratorio-network


networks:
  walaboratorio-network:
    driver: bridge
